[theme]
base = "light"
primaryColor = "#1d4935"
backgroundColor = "#f8faf7"
secondaryBackgroundColor = "#eef2ee"
textColor = "#17241d"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
